### ISSUE TITLE
Not working with youtube_13.34.50-1334502400_minAPI17(arm64-v8a)(nodpi)

### ISSUE THREAD

**Issue by Puatikskao** [wanam/YouTubeAdAway#102]
Hello I really appreciate your work on this project but sadly the new update isn't working for me. I installed YT 13.34.50 for my Samsung Galaxy A5 2017 running Android 7.1.2, but the hack does not work.  I've pasted fresh error logs below since I couldn't see an attachment option. Thanks! 

--
09-16 16:01:12.162 E/Xposed  (11531): java.lang.NoSuchMethodError: com.google.android.apps.youtube.app.WatchWhileActivity#a(android.content.Intent,boolean)#exact
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
09-16 16:01:12.162 E/Xposed  (11531):  	at name.mikanoshi.yourtubeplus.XposedMod.hookEverything(XposedMod.java:75)
09-16 16:01:12.162 E/Xposed  (11531):  	at name.mikanoshi.yourtubeplus.XposedMod.handleLoadPackage(XposedMod.java:59)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
09-16 16:01:12.162 E/Xposed  (11531):  	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-16 16:01:12.162 E/Xposed  (11531):  	at android.app.ActivityThread.-wrap2(ActivityThread.java)
09-16 16:01:12.162 E/Xposed  (11531):  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
09-16 16:01:12.162 E/Xposed  (11531):  	at android.os.Handler.dispatchMessage(Handler.java:102)
09-16 16:01:12.162 E/Xposed  (11531):  	at android.os.Looper.loop(Looper.java:154)
09-16 16:01:12.162 E/Xposed  (11531):  	at android.app.ActivityThread.main(ActivityThread.java:6236)
09-16 16:01:12.162 E/Xposed  (11531):  	at java.lang.reflect.Method.invoke(Native Method)
09-16 16:01:12.162 E/Xposed  (11531):  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
09-16 16:01:12.162 E/Xposed  (11531):  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
09-16 16:01:12.162 E/Xposed  (11531):  	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-16 16:01:12.172 E/Xposed  (11531): java.lang.NoSuchMethodError: nmj(tyt,java.lang.String,long)#exact
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.XposedHelpers.findConstructorExact(XposedHelpers.java:608)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.XposedHelpers.findAndHookConstructor(XposedHelpers.java:621)
09-16 16:01:12.172 E/Xposed  (11531):  	at com.datanasov.popupvideo.youtube.Mod.handleLoadPackage(Mod.java:134)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
09-16 16:01:12.172 E/Xposed  (11531):  	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-16 16:01:12.172 E/Xposed  (11531):  	at android.app.ActivityThread.-wrap2(ActivityThread.java)
09-16 16:01:12.172 E/Xposed  (11531):  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
09-16 16:01:12.172 E/Xposed  (11531):  	at android.os.Handler.dispatchMessage(Handler.java:102)
09-16 16:01:12.172 E/Xposed  (11531):  	at android.os.Looper.loop(Looper.java:154)
09-16 16:01:12.172 E/Xposed  (11531):  	at android.app.ActivityThread.main(ActivityThread.java:6236)
09-16 16:01:12.172 E/Xposed  (11531):  	at java.lang.reflect.Method.invoke(Native Method)
09-16 16:01:12.172 E/Xposed  (11531):  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
09-16 16:01:12.172 E/Xposed  (11531):  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
09-16 16:01:12.172 E/Xposed  (11531):  	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-16 16:01:12.262 I/Xposed  (11531): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3
